payment_vkey: "keys/payment-preprod.vkey"
payment_skey: "keys/payment-preprod.skey"

rewards_address: "keys/preprod.plutus"

inputs:
  - ecf472749b463dd2efa99e9ba1251a33d0b29a64608a78cd17a90a3024a6f683@0
